#!/bin/bash
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# SDDM Wallpaper Sync Script (Option A: Dynamic Sync)
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#
# This script syncs your current hyprlock wallpaper to SDDM.
# Run this script after changing wallpapers to keep SDDM in sync.
#
# Usage:
#   ./sync_sddm_wallpaper.sh
#
# Or add to your wallpaper change script:
#   ~/Scripts/sync_sddm_wallpaper.sh &
#
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

set -e

# Color codes for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Configuration
WALLPAPER_CACHE="$HOME/.cache/wall-cache/current_wallpaper"
SDDM_THEME_DIR="/usr/share/sddm/themes/silent"
SDDM_CONFIG_USER="$SDDM_THEME_DIR/configs/everforest.user.conf"

# Check if wallpaper cache exists
if [ ! -f "$WALLPAPER_CACHE" ]; then
    echo -e "${RED}❌ Error: Wallpaper cache not found at $WALLPAPER_CACHE${NC}"
    echo "   Make sure you have set a wallpaper using Super+Shift+W"
    exit 1
fi

# Read the wallpaper path
WALLPAPER_PATH=$(cat "$WALLPAPER_CACHE")

# Validate wallpaper file exists
if [ ! -f "$WALLPAPER_PATH" ]; then
    echo -e "${RED}❌ Error: Wallpaper file not found: $WALLPAPER_PATH${NC}"
    exit 1
fi

echo -e "${GREEN}📸 Found wallpaper: $(basename "$WALLPAPER_PATH")${NC}"

# Check if SDDM theme directory exists
if [ ! -d "$SDDM_THEME_DIR" ]; then
    echo -e "${RED}❌ Error: SDDM theme directory not found: $SDDM_THEME_DIR${NC}"
    echo "   Run ./install_sddm.sh first to install SilentSDDM theme"
    exit 1
fi

# Create user config override
echo "🔧 Updating SDDM configuration..."

sudo tee "$SDDM_CONFIG_USER" > /dev/null <<EOF
## ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## SDDM Everforest - User Configuration Override
## ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
## Auto-generated by ~/Scripts/sync_sddm_wallpaper.sh
## Last updated: $(date)
## ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

[General]
Background="$WALLPAPER_PATH"
EOF

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✅ SDDM wallpaper updated successfully!${NC}"
    echo ""
    echo "📋 Next steps:"
    echo "   - Changes will take effect at next login screen"
    echo "   - To test immediately: cd /usr/share/sddm/themes/silent && sudo ./test.sh"
    echo "   - Or switch to TTY and back: Ctrl+Alt+F2, then Ctrl+Alt+F1"
    echo ""
else
    echo -e "${RED}❌ Failed to update SDDM configuration${NC}"
    exit 1
fi

# Optional: Set permissions so SDDM can read the wallpaper
echo "🔐 Setting wallpaper permissions..."

# Get the wallpaper directory
WALLPAPER_DIR=$(dirname "$WALLPAPER_PATH")

# Set permissions using ACLs (more secure than chmod 755)
# This allows the 'sddm' user to access the file without opening your entire home directory

# Check if setfacl is available
if command -v setfacl &> /dev/null; then
    # Grant SDDM user read access to the wallpaper
    sudo setfacl -m u:sddm:r "$WALLPAPER_PATH" 2>/dev/null && \
        echo -e "${GREEN}✓ ACL permissions set for SDDM user${NC}" || \
        echo -e "${YELLOW}⚠️  Could not set ACL (wallpaper may not be visible at login)${NC}"

    # Grant execute permission on parent directories (needed for SDDM to traverse path)
    CURRENT_DIR="$WALLPAPER_DIR"
    while [ "$CURRENT_DIR" != "$HOME" ] && [ "$CURRENT_DIR" != "/" ]; do
        sudo setfacl -m u:sddm:x "$CURRENT_DIR" 2>/dev/null
        CURRENT_DIR=$(dirname "$CURRENT_DIR")
    done
    sudo setfacl -m u:sddm:x "$HOME" 2>/dev/null
    sudo setfacl -m u:sddm:x "$HOME/.cache" 2>/dev/null
    sudo setfacl -m u:sddm:x "$HOME/.cache/wall-cache" 2>/dev/null
else
    echo -e "${YELLOW}⚠️  setfacl not found. Using basic chmod instead...${NC}"
    # Fallback: Basic permissions (less secure)
    chmod 755 "$HOME" 2>/dev/null || true
    chmod 755 "$HOME/.cache" 2>/dev/null || true
    chmod 755 "$HOME/.cache/wall-cache" 2>/dev/null || true
    chmod 644 "$WALLPAPER_PATH" 2>/dev/null || true
    echo -e "${GREEN}✓ Basic permissions set${NC}"
fi

echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ Wallpaper sync complete!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
